name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        source venv/bin/activate
        flake8 .
    - name: Check formatting with black
      run: |
        source venv/bin/activate
        black --check .
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    - name: Install frontend dependencies
      run: |
        cd frontend
        npm ci
    - name: Lint frontend with ESLint
      run: |
        cd frontend
        npx eslint .
    - name: Set up environment variables for Django
      run: |
        echo "DJANGO_SECRET_KEY=test-secret-key" >> $GITHUB_ENV
        echo "DJANGO_DB_PATH=$(pwd)/db.sqlite3" >> $GITHUB_ENV
    - name: Run Django tests
      run: |
        source venv/bin/activate
        python manage.py test
    - name: Run tests with coverage
      run: |
        source venv/bin/activate
        pip install coverage
        coverage run manage.py test
        coverage report
        coverage xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
    # - name: Build Docker image (optional)
    #   run: docker build -t your-dockerhub-username/muon-telescope-project .
    # - name: Push Docker image (optional)
    #   run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin && docker push your-dockerhub-username/muon-telescope-project
